### ISSUE TITLE
Update to laravel 9

### ISSUE THREAD

**Issue by dukenst2006** [andyjoset/laravel-nuxt#1]
Hi @andyjoset 
Great work dude, this is a good nuxt starting project. Any plan to update it to laravel 9 ?
Could be able to add PWA capability by installing nuxt PWA module ?

Thanks for your efforts and keep it on brother !

**Comment by andyjoset** [comment]
Hi @dukenst2006 

Support for Laravel 9 is coming in next days, about PWA, the Nuxt module is installed but not configured yet.
